version: '3.8'

services:
  logan-dashboard:
    image: falkoro/logan-dashboard:latest
    container_name: logan-dashboard
    ports:
      - "100:5000"
    environment:
      - FLASK_ENV=production
      - SSH_HOST=localhost
      - SSH_USERNAME=logan
      - SSH_PORT=22
    volumes:
      # Mount SSH keys if needed (optional)
      # - ~/.ssh:/home/dashboard/.ssh:ro
      # Mount Docker socket for local Docker management (optional)
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - logan-network

networks:
  logan-network:
    driver: bridge
