version: '3.8'

services:
  dashboard:
    build: .
    image: docker-dashboard:latest
    container_name: docker-dashboard
    restart: unless-stopped
    ports:
      - "100:5000"
    environment:
      - FLASK_ENV=production
      - SSH_HOST=logan-GL502VS
      - SSH_USERNAME=logan
      - SSH_PORT=22
      - HOST=0.0.0.0
      - PORT=5000
      - LOG_LEVEL=INFO
    volumes:
      # Mount SSH key (create this path and add your SSH private key)
      - ~/.ssh:/home/dashboard/.ssh:ro
      # Mount logs directory
      - ./logs:/app/logs
      # Optional: Mount custom configuration
      - ./.env:/app/.env:ro
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dashboard-network:
    driver: bridge

volumes:
  dashboard-logs:
    driver: local
